### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by stepanleas** [filippotoso/laravel-domain-library#1]
When I require this package on a fresh Laravel 9 app, this error is thrown in the console.

    - filippo-toso/laravel-domain-library[v1.0.0, ..., v1.0.18] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires filippo-toso/laravel-domain-library ^1.0 -> satisfiable by filippo-toso/laravel-domain-library[v1.0.0, ..., v1.0.18].

In composer.json is `"laravel/framework": "^9.0"` and `"php": "^8.0.2"`

**Comment by filippotoso** [comment]
Try the latest version
