### ISSUE TITLE
laravel 9 issues

### ISSUE THREAD

**Issue by fabiobap** [filippotoso/laravel-domain-library#2]
I'm still having issues trying to install this package on a fresh project

` Problem 1
    - filippo-toso/laravel-domain-library[v1.0.0, ..., v1.0.18] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - filippo-toso/laravel-domain-library v1.0.19 requires league/flysystem ^1.1 -> found league/flysystem[1.1.0, ..., 1.x-dev] but the package is fixed to 3.0.11 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires filippo-toso/laravel-domain-library ^1.0 -> satisfiable by filippo-toso/laravel-domain-library[v1.0.0, ..., v1.0.19].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require filippo-toso/laravel-domain-library:*" to figure out if any version is installable, or "composer require filippo-toso/laravel-domain-library:^2.1" if you know which you need.`

my composer.json:

` "require": {
        "php": "^8.0.2",
        "guzzlehttp/guzzle": "^7.2",
        "inertiajs/inertia-laravel": "^0.5.4",
        "laravel/framework": "^9.2",
        "laravel/sanctum": "^2.8",
        "laravel/tinker": "^2.7",
        "tightenco/ziggy": "^1.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/breeze": "^1.8",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },`

**Comment by filippotoso** [comment]
Try with version 2.0.0
